##
  portainer:
    image: portainer/portainer-ce:2.17.1-alpine
    container_name: portainer
    hostname: 'portainer.$DOMAIN'
    restart: unless-stopped
    volumes:
      - /data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portainer
    ports:
      - 127.0.0.1:6061:9000
