.PHONY: clean
clean: clean-latest clean-version clean-snapshot clean-alpha clean-beta clean-build

.PHONY: build
build: compile build-others build-dist

.PHONY: watch
watch: watch-src

.PHONY: test
test: clean compile unit-tests

.PHONY: e2e
e2e: clean build e2e-tests

#######################################################################
## Tasks

### current version number
VERSION := $(shell cat VERSION)
### watcher in seconds
WATCHER := 2
### watcher mode: debug | silent
mode    := silent

.PHONY: clean-build
clean-build:
	(rm -rf ./build/)

.PHONY: clean-latest
clean-latest:
	(rm -rf ./dist/latest/)

.PHONY: clean-snapshot
clean-snapshot:
	(rm -rf ./dist/${VERSION}-SNAPSHOT/)

.PHONY: clean-alpha
clean-alpha:
	(rm -rf ./dist/${VERSION}a/)

.PHONY: clean-beta
clean-beta:
	(rm -rf ./dist/${VERSION}b/)

.PHONY: clean-version
clean-version:
	(rm -rf ./dist/${VERSION}/)

.PHONY: build-others
build-others:
	((cp ./LICENSE ./build/) && \
	 (cp ./src/main/resources/README.txt ./build/) && \
	 (cp ./VERSION ./build/))

.PHONY: build-dist
build-dist:
	((mkdir -p dist/) && \
	 (cp -r ./build/ ./dist/${VERSION}/) && \
	 (cp -r ./dist/${VERSION}/ ./dist/latest/))

.PHONY: compile
compile: compile-bin compile-res compile-examples compile-make

.PHONY: compile-res
compile-res:
	((rm -rf ./build/resources/) && \
	 (mkdir -p ./build/resources/) && \
	 (rm -rf ./build/tmp/resources/) && \
	 (mkdir -p ./build/tmp/resources/) && \
	 (find ./src/main/resources/ -name 'docker-compose.env' -exec cp "{}" ./build/resources/ \;) && \
	 (find ./src/main/resources/ -name 'docker-compose.*.yml' -exec cp "{}" ./build/tmp/resources/ \;))

.PHONY: compile-examples
compile-examples:
	((rm -rf ./build/examples/) && \
	 (mkdir -p ./build/examples/) && \
	 (find ./src/main/sh/ -name 'main.ini' -exec cp "{}" ./build/examples/make.ini.example \;) && \
	 (find ./src/main/resources/ -name '*.example' -exec cp "{}" ./build/examples/ \;))

.PHONY: compile-bin
compile-bin:
	((rm -rf ./build/tmp/bin/) && \
	 (mkdir -p ./build/tmp/bin/) && \
	 (find ./src/main/sh/app/commands/ -name '*.sh' -exec cp "{}" ./build/tmp/bin/ \;) && \
	 (find ./src/main/sh/app/tasks/ -name '*.sh' -exec cp "{}" ./build/tmp/bin/ \;) && \
	 (find ./src/main/sh/utils/ -name '*.sh' -exec cp "{}" ./build/tmp/bin/ \;) && \
	 (find ./src/main/sh/ -name 'main.sh' -exec cp "{}" ./build/tmp/bin/ \;))

.PHONY: compile-make
compile-make:
	((cp ./lib/ldu-devops-compiler/ldu-devops-compiler-1.0.0b.sh ./build/tmp/compiler.sh) && \
	 (chmod 755 ./build/tmp/compiler.sh) && \
	 (./build/tmp/compiler.sh "../") && \
	 (chmod 755 ./build/make.sh) && \
	 (rm -rf ./build/tmp/))

.PHONY: watch-src
watch-src:
	(if [ "${mode}" = "silent" ]; then \
		watch -n ${WATCHER} make compile --silent; \
	 else \
		watch -n ${WATCHER} make compile; \
	 fi)

.PHONY: unit-tests
unit-tests:
	((chmod -R 755 ./src/test/sh/unit/*.sh) && \
	 (/bin/bash ./src/test/sh/unit/run-all.sh ${test} ${args}))

.PHONY: e2e-tests
e2e-tests:
	((chmod -R 755 ./src/test/sh/integration/*.sh) && \
	 (/bin/bash ./src/test/sh/integration/run-all.sh ${test} ${args}))

.PHONY: release
release:
	((make clean build) && \
	 (git add VERSION && git commit -m "RELEASE: Version bumped to v${VERSION}") && \
	 (git add CHANGELOG.md && git commit -m "CHORE: Autogenerated CHANGELOG for v${VERSION}") && \
	 (git add --all dist/* && git commit -m "CHORE: Autogenerated DIST files for v${VERSION}") && \
	 (git-flow release finish ${VERSION}) && \
	 (git push --all && git push --tags))
