##
  mysql:
    image: mysql:8-debian
    container_name: mysql
    hostname: 'mysql.$DOMAIN'
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_USER=$MYSQL_ROOT_USER
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - /data/mysql/db:/var/lib/mysql
    networks:
      - mysql

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: phpmyadmin
    hostname: 'phpmyadmin.$DOMAIN'
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - mysql
    ports:
      - 127.0.0.1:6064:8081
    depends_on:
      - mysql
