##
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    hostname: 'postgres.$DOMAIN'
    restart: unless-stopped
    environment:
      - PGDATA=/data/postgres
      - POSTGRES_USER=$POSTGRES_ROOT_USER
      - POSTGRES_PASSWORD=$POSTGRES_ROOT_PASSWORD
    volumes:
      - /data/postgres/data:/var/lib/postgresql/data
      - /data/postgres/db:/data/postgres
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:6.21
    container_name: pgadmin
    hostname: 'pgadmin.$DOMAIN'
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=$POSTGRES_PGADMIN_USER
      - PGADMIN_DEFAULT_PASSWORD=$POSTGRES_PGADMIN_PASSWORD
    networks:
      - postgres
    ports:
      - 127.0.0.1:6065:8081
    depends_on:
      - postgres
